services:
  mysql:
    image: mysql:8.0
    container_name: onlinebanking-db
    environment:
      MYSQL_DATABASE: onlinebanking
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_PASSWORD: rootroot
    ports:
      - "3307:3307"
    volumes:
      - ./mysql_data:/var/lib/mysql
