spring:
  application:
    name: OnlineBankingSystemP
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
  mail:
    host: ${EMAIL_HOST}
    password: ${EMAIL_PASSWORD}
    username: ${EMAIL_SENDER}
    port: ${EMAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  file:
    name: log/appLog.log
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 6020
  error:
    include-message: always